/*
  globe.js — Real threat-globe + live ticker for the SOC resume background.
  DATA IS REAL: points come from attack-feed.json, generated by geo-feed.js
  from FireHOL blocklists (real malicious/abusive source IPs, geocoded).
  - Globe: dark sphere + real hotspot points + animated arcs (illustrative traffic).
  - Ticker: streams the REAL scraped entries (IP · country · list) so it is
    genuinely "live threat intel", not fabricated events.
*/
(function () {
  if (typeof THREE === "undefined" || typeof Globe === "undefined") return;
  if (window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

  var el = document.getElementById("globeViz");
  if (!el) return;

  var FEED_URL = "attack-feed.json?t=" + Date.now();

  function loadFeed(cb) {
    fetch(FEED_URL)
      .then(function (r) { return r.ok ? r.json() : Promise.reject(); })
      .then(function (j) { cb(null, j); })
      .catch(function () { cb(new Error("feed unavailable")); });
  }

  function buildGlobe(feed) {
    var pts = (feed.points || []).filter(function (p) { return p.lat && p.lon; });
    if (!pts.length) return;

    var globe = Globe()(el)
      .backgroundColor("rgba(0,0,0,0)")
      .showAtmosphere(true)
      .atmosphereColor("#2ee6a6")
      .atmosphereAltitude(0.18)
      .globeMaterial(new THREE.MeshPhongMaterial({ color: "#0a141c", emissive: "#06121a", shininess: 6 }))
      .pointsData(pts)
      .pointLat(0.5) // placeholder; real accessor set below
      .pointLng(function () { return 0; })
      .pointLat(function () { return 0; })
      .pointColor(function () { return "rgba(46,230,166,0.9)"; })
      .pointAltitude(0.01)
      .pointRadius(0.28)
      .pointsMerge(false);

    // correct accessors (function refs set after init)
    globe.pointLat(function (d) { return d.lat; }).pointLng(function (d) { return d.lon; });

    // lighting
    var scene = globe.scene();
    var light = new THREE.DirectionalLight(0x9fe8ff, 1.1);
    light.position.set(1, 1, 1);
    scene.add(light);
    scene.add(new THREE.AmbientLight(0x335577, 0.6));

    // size
    function resize() { globe.width(window.innerWidth).height(window.innerHeight); }
    resize();
    window.addEventListener("resize", resize);

    // gentle auto-rotate
    globe.controls().autoRotate = true;
    globe.controls().autoRotateSpeed = 0.45;
    globe.controls().enableZoom = false;
    globe.controls().enablePan = false;

    // animated arcs between random real points (illustrative of attack volume/direction)
    var arcs = [];
    function makeArcs() {
      arcs = [];
      var n = Math.min(24, Math.floor(pts.length / 4));
      for (var i = 0; i < n; i++) {
        var a = pts[Math.floor(Math.random() * pts.length)];
        var b = pts[Math.floor(Math.random() * pts.length)];
        if (a === b) continue;
        arcs.push({ startLat: a.lat, startLng: a.lon, endLat: b.lat, endLng: b.lon, t: Math.random() });
      }
      globe.arcsData(arcs)
        .arcColor(function () { return ["rgba(56,189,248,0.05)", "rgba(46,230,166,0.55)"]; })
        .arcDashLength(0.4)
        .arcDashGap(0.6)
        .arcDashAnimateTime(2400)
        .arcStroke(0.25)
        .arcAltitude(0.25);
    }
    makeArcs();
    setInterval(makeArcs, 8000); // refresh arcs so it feels alive
  }

  // ---- bottom ticker: REAL scraped attack entries, seamless loop ----
  function wireTicker(feed) {
    var track = document.getElementById("tickerTrack");
    if (!track) return;
    var pts = (feed.points || []).filter(function (p) { return p.ip && p.country; });
    if (!pts.length) return;

    function entryText(p) {
      var ip = p.ip, cc = p.cc || "", c = p.country || "?";
      var tag = (p.tag || "").replace("firehol_", "");
      return ip + "  ·  " + c + " " + cc + "  ·  " + tag;
    }
    function copyHtml() {
      var html = '<div class="ticker-copy">';
      for (var i = 0; i < pts.length; i++) {
        var p = pts[i];
        var cls = p.tag && /abuse|anonymous/.test(p.tag) ? "warn" : "";
        html += '<span class="' + cls + '">[src] ' + esc(entryText(p)) + "</span>";
      }
      return html + "</div>";
    }
    // two identical copies -> CSS translateX(-50%) loops with no seam
    track.innerHTML = copyHtml() + copyHtml();
  }

  function esc(s) {
    return String(s).replace(/[&<>"]/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c];
    });
  }

  loadFeed(function (err, feed) {
    if (err || !feed) return;
    buildGlobe(feed);
    wireTicker(feed);
    // refresh data periodically (the backend refreshes attack-feed.json on a schedule)
    setInterval(function () { loadFeed(function (e2, f2) { if (!e2 && f2) { buildGlobe(f2); wireTicker(f2); } }); }, 10 * 60 * 1000);
  });
})();
